### ISSUE TITLE
issue with install using POD

### ISSUE THREAD

**Issue by pkgundam** [tskulbru/NBMaterialDialogIOS#1]
Hi -  thank you for the library.

Here is the issue while installing the library 

BKs-MacBook-Pro:PageView pk$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
[!] Unable to find a specification for `NBMaterialDialog (~> 0.2.1)`

**Comment by pkgundam** [comment]
this one worked

pod 'BFPaperButton', '~> 2.0.18'
pod 'NBMaterialDialogIOS'

thanks,
Phani

**Comment by tskulbru** [comment]
You are absolutely correct, I had forgotten to update the readme to the new name. Sorry for the inconvenience!

**Comment by pkgundam** [comment]
sure, no worries. Thank you for the beautiful library.

**Comment by pkgundam** [comment]
Hi - can you provide a dialog with text input?

Thank you

**Comment by tskulbru** [comment]
Hm, I guess I technically could create a default dialog with text input. However in many (if not most) cases people tend to want to use either a custom library for their input fields, or something different regarding styling. You should be able to extend `NBMaterialDialog` to include a input dialog just the way you want it. If I were to make one I would either need to include another library dependency or use the apple standard inputfield (both of which are not ideal).

If you still want one, feel free to create a new issue requesting one, and if it gets enough "votes" i will make one

**Comment by pkgundam** [comment]
sure, thank you buddy. I will try that
