### ISSUE TITLE
Clicks onto the dialog close it

### ISSUE THREAD

**Issue by rockwotj** [tskulbru/NBMaterialDialogIOS#3]
If I click onto the whitespace of an alert dialog, or even the title, then it closes the dialog. Is there a way to disable this, so the only way to dismiss this is the buttons or clicking off the dialog?

Thanks for the great library!

**Comment by tskulbru** [comment]
Thank you for your report! This was indeed a bug, and has been fixed in the newest version 0.2.2 (just released). Glad you enjoy my library!
