### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by tskulbru** [tskulbru/NBMaterialDialogIOS#6]

**Comment by Gerst20051** [comment]
Did you create a branch or PR?

**Comment by tskulbru** [comment]
Neither, I havent gotten around to it yet. Feel free to do it! :)

**Comment by Gerst20051** [comment]
I did just forgot to update this. I wouldn't merge it as is I just needed to update my projects to Swift 3.

MR: https://github.com/tskulbru/NBMaterialDialogIOS/pull/9
Branch: https://github.com/Gerst20051/NBMaterialDialogIOS/tree/swift3

**Comment by tskulbru** [comment]
OK, so you've just run the auto converter in xcode? In any case, I'll take a look at it and see

**Comment by tskulbru** [comment]
Released a Swift 3.0 compatible version. 345cdb1
